# Site settings
title: Casa Rosales
description: Sausages! Made daily locally from only the finest ingredients and delivered FRESH, not frozen, to your neighborhood store.
url: "http://adrianmiller.design/casa-rosales"

# Build settings
markdown: kramdown

exclude: ["README.md"]

# SASS Dir
sass:
    sass_dir: assets